```{r}
library(RsienaTwoStep)
library(igraph)
```
```{r}
# ts_net1
# ts_net1 + t(ts_net1)
```
```{r}
# (m2 <- matrix(1:20, 4, 5))
# lower.tri(m2)
# m2[lower.tri(m2)] <- NA
# m2
```


```{r}


T1 <- s501
diag(T1)=NA
T1_up <- T1
T1_up[lower.tri(T1_up)] <- NA

T1_low <- T1
T1_up[upper.tri(T1_up)] <- NA

ID_up <- reshape2::melt(T1)
ID_up$iden <- ifelse(is.na(ID_up$value),NA,"upper.tri") 

ID_low <- reshape2::melt(T1_low)
ID_low$iden <- ifelse(is.na(ID_low$value),NA,"lower.tri") 

T1_full <- rbind(ID_up, ID_low)
T1_full <- T1_full[,c("Var1", "Var2", "iden", "value")]
T1_full <- T1_full[rowSums(is.na(T1_full))==0,]


dft1 <- T1_full[order(T1_full$Var1),]
dft1$value2 <- T1_full$value[order(T1_full$Var2)]

rownames(dft1) <- NULL
colnames(dft1) <- c("ego", "alter", "iden", "outgoing", "incoming")

for(x in 1:nrow(dft1)){
  if(dft1$outgoing[x] == 0 & dft1$incoming[x] == 0){
    dft1$tie_struc[x] <- "NULL"
  } else if (dft1$outgoing[x] == 1 & dft1$incoming[x] == 0){
    dft1$tie_struc[x] <- "10"
  } else if (dft1$outgoing[x] == 0 & dft1$incoming[x] == 1){
    dft1$tie_struc[x] <- "01"
  } else if (dft1$outgoing[x] == 1 & dft1$incoming[x] == 1){
    dft1$tie_struc[x] <- "MUTUAL"
  }
  x+1
}# bla1 <- dft1

dft1 <- subset(dft1, iden == "lower.tri")


```
##Create t2 frame
```{r}



checkt2 <- s502
diag(check)=NA

ID_up <- reshape2::melt(checkt2)[as.vector(upper.tri(checkt2)),]
ID_up$iden <- "upper.tri" 
ID_low <- reshape2::melt(checkt2)[as.vector(upper.tri(checkt2)),]
ID_low$iden <- "lower.tri" 

testt2 <- rbind(ID_up, ID_low)
testt2 <- testt2[,c("Var1", "Var2", "iden", "value")]

test_filtert2 <- testt2[rowSums(is.na(testt2))==0,]


dft2 <- test_filtert2[order(test_filtert2$Var1),]
dft2$value2 <- test_filter$value[order(test_filtert2$Var2)]

rownames(dft2) <- NULL
colnames(dft2) <- c("ego", "alter", "iden", "outgoing", "incoming")

for(x in 1:nrow(dft2)){
  if(dft2$outgoing[x] == 0 & dft2$incoming[x] == 0){
    dft2$tie_struc[x] <- "NULL"
  } else if (dft2$outgoing[x] == 1 & dft2$incoming[x] == 0){
    dft2$tie_struc[x] <- "10"
  } else if (dft2$outgoing[x] == 0 & dft2$incoming[x] == 1){
    dft2$tie_struc[x] <- "01"
  } else if (dft2$outgoing[x] == 1 & dft2$incoming[x] == 1){
    dft2$tie_struc[x] <- "MUTUAL"
  }
  x+1
}# bla1 <- dft2

df_change <- cbind(dft1, dft2$tie_struc)

dft2 %>% dplyr::count(tie_struc)

dft2 <- subset(dft2, iden == "upper.tri")

dft2 %>% dplyr::count(tie_struc)
```


```{r}
df_change <- cbind(dft1, dft2$tie_struc)

tR <- table(df_change$tie_struc, df_change$`dft2$tie_struc`)

  colnames(tR) = c("Assym_out", "Assym_in", "Mutual", "Null")
  rownames(tR) = c("Assym_out", "Assym_in", "Mutual", "Null")

  tR
```


```{r}
net1g <- graph_from_adjacency_matrix(s501, mode = "directed")
coords <- layout_(net1g, nicely())  #let us keep the layout
par(mar = c(0.1, 0.1, 0.1, 0.1))
{
  plot.igraph(net1g, layout = coords)
  graphics::box()
}
net1g




```

```{r} 

ts_net1
sna::dyad.census(ts_net1)

as.vector(upper.tri(ts_net1))

check <- ts_net1 + t(ts_net1)

test <- reshape2::melt(check)[as.vector(upper.tri(ts_net1)),]
test2 <- reshape2::melt(check)[as.vector(lower.tri(ts_net1)),]



reshape2::melt((ts_net1 + t(ts_net1)))[as.vector(upper.tri(ts_net1)),]


dyad.census.ind <- function(x) {
  df <- reshape2::melt((x + t(x)))[as.vector(upper.tri(x)),]
  df <- df[order(df$Var1),]
  rownames(df) <- NULL
  colnames(df) <- c("ego", "alter", "tie")
  return(df)
}


ts_net1_t2 <- ts_net1
ts_net1_t2[1,4] <- 1 
ts_net1_t2[4,1] <- 1 



dft1 <- dyad.census.ind(ts_net1)
dft2 <- dyad.census.ind(ts_net1_t2)

dft1$tiet2 <- dft2$tie
dft1
table(dft1$tie, dft1$tiet2)
```

```{r}
#op basis van rsienaworkflow vignette


dyad.census.ind <- function(x) {
  df <- reshape2::melt((x + t(x)))[as.vector(upper.tri(x)),]
  df <- df[order(df$Var1),]
  rownames(df) <- NULL
  colnames(df) <- c("ego", "alter", "tie")
  return(df)
}


#reality

t2 <- s502
t1 <- s501

dft1 <- dyad.census.ind(t1)
dft2 <- dyad.census.ind(t2)

dft1$tiet2 <- dft2$tie
dft1
tR <- table(dft1$tie, dft1$tiet2)

#simultaneity
t2 <- ts_ansSp3$simnets[[3]]
t1 <- s501

dft1 <- dyad.census.ind(t1)
dft2 <- dyad.census.ind(t2)

dft1$tiet2 <- dft2$tie
dft1
tS <- table(dft1$tie, dft1$tiet2)

#strong coordination
t2 <- ts_ansSCp3$simnets[[3]]
t1 <- s501

dft1 <- dyad.census.ind(t1)
dft2 <- dyad.census.ind(t2)

dft1$tiet2 <- dft2$tie
dft1
tSC <- table(dft1$tie, dft1$tiet2)

tR
tS
tSC

```



